### ISSUE TITLE
执行script/install.sh失败

### ISSUE THREAD

**Issue by Tk-archer** [xunuoi/gulpman#3]
npm install gulpman 过程中
执行script/install.sh 失败
失败提示
`scripts/install.sh: 6: scripts/install.sh: Syntax error: Bad fd number`

根据排查是`gulp -v >& /dev/null`的问题
原因是shell语法不兼容
将`>& /dev/null`更改成`/dev/null 2>&1`可正常执行
建议对不同shell做兼容处理=。=

**Comment by xunuoi** [comment]
@Tk-archer 稍后就修复，多谢对Shell的指点！兼容性确实需要好好做一下：）

**Comment by xunuoi** [comment]
@Tk-archer 你用的shell类型是哪种？

**Comment by xunuoi** [comment]
@Tk-archer 已修复为 `>/dev/null 2>&1` 这个语法兼容性应该没问题了，可以再试下安装 ：）
